### ISSUE TITLE
There is a string that cannot be translated in GC5.0

### ISSUE THREAD

**Issue by cary-rowen** [josephsl/goldenCursor#8]
On line 348, it can be translated if it is changed to the following:
			gui.mainFrame, _("Enter the name for the current mouse position (x: {x}, Y: {y})").format(x=x, y=y),

**Comment by josephsl** [comment]
Hi, ah yes, I knew there were messages like this… I’ll deploy a fix for translators tonight. Thanks.

**Comment by cary-rowen** [comment]
OK, thank you for your efforts
